title: MinecraftHopper
email: admin@minecrafthopper.net
description: >-
  Get community help for Minecraft
baseurl: ""
url: "https://minecrafthopper.net"
twitter_username: ""
github_username:  ""

markdown: kramdown
theme: just-the-docs

collections:
    help:
        output: true

plugins:
  - jekyll-redirect-from